version: '3'
services:
  api:
    container_name: rtg-api
    build: 
      context: .
      dockerfile: ./api/Dockerfile
    restart: always
    tty: true
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: rtg-db
    stdin_open: true
    tty: true
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/initdb:/docker-entrypoint-initdb.d
